layout_spectrum: 0.9731183
color:
  saturation: 0.8064516
  lightness: 0.6612903
  brandStrength: 0.8261649
  rhythmicContrast: 0.4247312
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.123871
name: David La Cava Creative
